apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
    - name: mysql
      image: mysql:latest
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_DATABASE
      resources:
        requests:
          cpu: 0.5
          memory: 1Gi   # kubectl top pod 觀測到的值是 4XX M，希望讓平常使用率維持在 60%
        limits:
          cpu: 1       # be request value 2 times
          memory: 1.5Gi   # be request value 2 times
      livenessProbe:      
        tcpSocket:
         port: 3306
        initialDelaySeconds: 30 # 觀看 log，啟動時間大約需 15~25 秒
        timeoutSeconds: 5
      readinessProbe:
        tcpSocket:
         port: 3306
        timeoutSeconds: 5
  restartPolicy: OnFailure    # DB 應只有在 error 時才重啟
