apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    version: "1"
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx:latest
      volumeMounts:
        - mountPath: /etc/nginx/
          name: nginx-conf
        - mountPath: /var/log/nginx/
          name: logs-volume
    - name: fluentd
      image: fluentd:latest
      volumeMounts:
        - mountPath: /logs
          name: logs-volume
        - mountPath: /fluentd/etc/
          name: fluentd-conf
      resources:
        requests:
          cpu: 100m       
          memory: 150Mi
        limits:
          cpu: 200m    
          memory: 300Mi
      livenessProbe:      
        timeoutSeconds: 5
      readinessProbe:
        timeoutSeconds: 5
  restartPolicy: Always
  volumes:
    - name: nginx-conf
      configMap:
        name: conf
        items:
          - key: nginx.conf
            path: nginx.conf
    - name: fluentd-conf
      configMap:
        name: conf
        items:
          - key: fluent.conf
            path: fluent.conf
    - name: logs-volume
      emptyDir: {}
        
      
