apiVersion: v1
kind: Pod
metadata:
  name: wp
  labels:
    version: "1"
    app: wp
spec:
  containers:
    - name: wp
      image: wordpress:latest
      env:
        - name: WORDPRESS_DB_HOST
          value: mysql-svc
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_DATABASE
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_USER
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
      resources:
        requests:
          cpu: 100m       
          memory: 200Mi
        limits:
          cpu: 200m    
          memory: 400Mi
  restartPolicy: Always